<?php

/**
 * ListnerConfigStreamFiltersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListnerConfigStreamFiltersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListnerConfigStreamFiltersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListnerConfigStreamFilters');
    }
}