<?php

/**
 * ListnerConfigTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListnerConfigTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListnerConfigTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ListnerConfig');
    }
}