<?php

/**
 * ListnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ListnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ListnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Listner');
    }
}