<?php

/**
 * StreamFilterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StreamFilterTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StreamFilterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StreamFilter');
    }
}