<?php

/**
 * VirtualServiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VirtualServiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VirtualServiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VirtualService');
    }
}