<?php

/**
 * VirtualServiceListnerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VirtualServiceListnerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VirtualServiceListnerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VirtualServiceListner');
    }
}