<?php

/**
 * VirtualServiceListnersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VirtualServiceListnersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VirtualServiceListnersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VirtualServiceListners');
    }
}