<?php

/**
 * BaseStreamFilter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $module_value
 * @property boolean $has_forward_mode
 * @property boolean $has_reverse_mode
 * @property Doctrine_Collection $ListnerConfigStreamFilters
 * 
 * @method string              getName()                       Returns the current record's "name" value
 * @method string              getModuleValue()                Returns the current record's "module_value" value
 * @method boolean             getHasForwardMode()             Returns the current record's "has_forward_mode" value
 * @method boolean             getHasReverseMode()             Returns the current record's "has_reverse_mode" value
 * @method Doctrine_Collection getListnerConfigStreamFilters() Returns the current record's "ListnerConfigStreamFilters" collection
 * @method StreamFilter        setName()                       Sets the current record's "name" value
 * @method StreamFilter        setModuleValue()                Sets the current record's "module_value" value
 * @method StreamFilter        setHasForwardMode()             Sets the current record's "has_forward_mode" value
 * @method StreamFilter        setHasReverseMode()             Sets the current record's "has_reverse_mode" value
 * @method StreamFilter        setListnerConfigStreamFilters() Sets the current record's "ListnerConfigStreamFilters" collection
 * 
 * @package    webadmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStreamFilter extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stream_filter');
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('module_value', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('has_forward_mode', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('has_reverse_mode', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ListnerConfigStreamFilters', array(
             'local' => 'id',
             'foreign' => 'stream_filter_id'));
    }
}