<?php

/**
 * BaseListnerConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property boolean $enable_gzip
 * @property string $filter_headers
 * @property enum $fwd_proxy_auth
 * @property string $lb_pool
 * @property string $lb_proxy_host
 * @property int $lb_backend_port
 * @property Doctrine_Collection $Listner
 * @property Doctrine_Collection $ListnerConfigStreamFilters
 * 
 * @method boolean             getEnableGzip()                 Returns the current record's "enable_gzip" value
 * @method string              getFilterHeaders()              Returns the current record's "filter_headers" value
 * @method enum                getFwdProxyAuth()               Returns the current record's "fwd_proxy_auth" value
 * @method string              getLbPool()                     Returns the current record's "lb_pool" value
 * @method string              getLbProxyHost()                Returns the current record's "lb_proxy_host" value
 * @method int                 getLbBackendPort()              Returns the current record's "lb_backend_port" value
 * @method Doctrine_Collection getListner()                    Returns the current record's "Listner" collection
 * @method Doctrine_Collection getListnerConfigStreamFilters() Returns the current record's "ListnerConfigStreamFilters" collection
 * @method ListnerConfig       setEnableGzip()                 Sets the current record's "enable_gzip" value
 * @method ListnerConfig       setFilterHeaders()              Sets the current record's "filter_headers" value
 * @method ListnerConfig       setFwdProxyAuth()               Sets the current record's "fwd_proxy_auth" value
 * @method ListnerConfig       setLbPool()                     Sets the current record's "lb_pool" value
 * @method ListnerConfig       setLbProxyHost()                Sets the current record's "lb_proxy_host" value
 * @method ListnerConfig       setLbBackendPort()              Sets the current record's "lb_backend_port" value
 * @method ListnerConfig       setListner()                    Sets the current record's "Listner" collection
 * @method ListnerConfig       setListnerConfigStreamFilters() Sets the current record's "ListnerConfigStreamFilters" collection
 * 
 * @package    webadmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListnerConfig extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('listner_config');
        $this->hasColumn('enable_gzip', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('filter_headers', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('fwd_proxy_auth', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'none',
              1 => 'mneisa',
              2 => 'mysql',
             ),
             'notnull' => true,
             'default' => 'none',
             ));
        $this->hasColumn('lb_pool', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('lb_proxy_host', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('lb_backend_port', 'int', null, array(
             'type' => 'int',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Listner', array(
             'local' => 'id',
             'foreign' => 'config_id'));

        $this->hasMany('ListnerConfigStreamFilters', array(
             'local' => 'id',
             'foreign' => 'listner_config_id'));
    }
}