<?php

/**
 * BaseListnerConfigStreamFilters
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $listner_config_id
 * @property bigint $stream_filter_id
 * @property ListnerConfig $ListnerConfig
 * @property StreamFilter $StreamFilter
 * 
 * @method bigint                     getListnerConfigId()   Returns the current record's "listner_config_id" value
 * @method bigint                     getStreamFilterId()    Returns the current record's "stream_filter_id" value
 * @method ListnerConfig              getListnerConfig()     Returns the current record's "ListnerConfig" value
 * @method StreamFilter               getStreamFilter()      Returns the current record's "StreamFilter" value
 * @method ListnerConfigStreamFilters setListnerConfigId()   Sets the current record's "listner_config_id" value
 * @method ListnerConfigStreamFilters setStreamFilterId()    Sets the current record's "stream_filter_id" value
 * @method ListnerConfigStreamFilters setListnerConfig()     Sets the current record's "ListnerConfig" value
 * @method ListnerConfigStreamFilters setStreamFilter()      Sets the current record's "StreamFilter" value
 * 
 * @package    webadmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseListnerConfigStreamFilters extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('listner_config_stream_filters');
        $this->hasColumn('listner_config_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
        $this->hasColumn('stream_filter_id', 'bigint', null, array(
             'type' => 'bigint',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ListnerConfig', array(
             'local' => 'listner_config_id',
             'foreign' => 'id'));

        $this->hasOne('StreamFilter', array(
             'local' => 'stream_filter_id',
             'foreign' => 'id'));
    }
}