<?php

/**
 * BaseVirtualService
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property boolean $enabled_status
 * @property Doctrine_Collection $VirtualServiceListners
 * 
 * @method string              getName()                   Returns the current record's "name" value
 * @method boolean             getEnabledStatus()          Returns the current record's "enabled_status" value
 * @method Doctrine_Collection getVirtualServiceListners() Returns the current record's "VirtualServiceListners" collection
 * @method VirtualService      setName()                   Sets the current record's "name" value
 * @method VirtualService      setEnabledStatus()          Sets the current record's "enabled_status" value
 * @method VirtualService      setVirtualServiceListners() Sets the current record's "VirtualServiceListners" collection
 * 
 * @package    webadmin
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVirtualService extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('virtual_service');
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'length' => 60,
             ));
        $this->hasColumn('enabled_status', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('VirtualServiceListners', array(
             'local' => 'id',
             'foreign' => 'virtual_service_id'));
    }
}